---
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "github.com/docker/docker"
    - dependency-name: "github.com/sassoftware/go-rpmutils"
    - dependency-name: "github.com/testcontainers/testcontainers-go"
    - dependency-name: "github.com/vifraa/gopom"
  allow:
  # Allow both direct and indirect updates for all packages
  - dependency-type: "all"
